POST http://localhost:1999/api/auth/register
Content-Type: application/json

{
    "classname": "C",
    "email": "jackfall1n@gmail.com",
    "password": "11111111",
    "role": "student",
    "username": "jack fallin"
}

# POST http://localhost:1999/api/classes/new
# Content-Type: application/json

# {
#     "classname": "E"
# }